name: Build and Publish Repo session-cleaner

on:
  workflow_dispatch:

permissions:
  contents: read  # Needed to read Repo B source
  packages: write # Needed to publish Repo B packages

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout Repo
      - uses: actions/checkout@v5

      # 2️⃣ Setup Java and Maven cache
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: maven

      - name: Set dynamic verion
        run: mvn versions:set -DnewVersion=1.0.$(date +%Y%m%d%H%M%S) -f pom-self.xml
      # 4️⃣ Build Repo project
      - name: Build Project
        run: mvn clean install -X -DskipTests -f pom-self.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      # 5️⃣ Publish Repo artifact to GitHub Packages
      - name: Publish to GitHub Packages
        run: mvn deploy --batch-mode -DskipTests -f pom-self.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
